### ISSUE TITLE
pump.io 2.1.1: OAuth login fails with " 'remoterequesttoken' with id 'undefined/*' "

### ISSUE THREAD

**Issue by clacke** [pump-io/pump.io#1280] opened 2017-02-15 20:06 UTC
I tried to login as clacke@datamost.com on [https://mipump.es/main/remote](https://mipump.es/main/remote). Output in the web browser was:

```
NoSuchThingError: No such 'remoterequesttoken' with id 'undefined/guc1GZVNdDDJlfwJEGoIXg'
   at /opt/pump.io/node_modules/databank-mongodb/lib/mongodb.js:389:30
   at handleCallback (/opt/pump.io/node_modules/mongodb/lib/utils.js:96:12)
   at /opt/pump.io/node_modules/mongodb/lib/collection.js:1403:5
   at handleCallback (/opt/pump.io/node_modules/mongodb/lib/utils.js:96:12)
   at /opt/pump.io/node_modules/mongodb/lib/cursor.js:675:5
   at handleCallback (/opt/pump.io/node_modules/mongodb-core/lib/cursor.js:172:5)
   at setCursorNotified (/opt/pump.io/node_modules/mongodb-core/lib/cursor.js:517:3)
   at /opt/pump.io/node_modules/mongodb-core/lib/cursor.js:590:16
   at queryCallback (/opt/pump.io/node_modules/mongodb-core/lib/cursor.js:254:5)
   at /opt/pump.io/node_modules/mongodb-core/lib/connection/pool.js:436:18 
```

When this problem occurs, this is how it looks in the server log:

```
TypeError: Cannot set property host of #<IncomingMessage> which has only a getter
    at Function.<anonymous> (/usr/lib/node_modules/pump.io/routes/web.js:714:26)
    at next (/usr/lib/node_modules/pump.io/node_modules/step/lib/step.js:51:23)
    at /usr/lib/node_modules/pump.io/node_modules/databank/lib/databankobject.js:110:33
    at DatabankObject.passThru0 (/usr/lib/node_modules/pump.io/node_modules/databank/lib/databankobject.js:44:5)
    at /usr/lib/node_modules/pump.io/node_modules/databank/lib/databankobject.js:106:27
    at /usr/lib/node_modules/databank-mongodb/lib/mongodb.js:392:21
    at handleCallback (/usr/lib/node_modules/databank-mongodb/node_modules/mongodb/lib/utils.js:96:12)
    at /usr/lib/node_modules/databank-mongodb/node_modules/mongodb/lib/collection.js:1403:5
    at handleCallback (/usr/lib/node_modules/databank-mongodb/node_modules/mongodb/lib/utils.js:96:12)
    at /usr/lib/node_modules/databank-mongodb/node_modules/mongodb/lib/cursor.js:675:5
{"name":"pump.io","hostname":"datamost.com","pid":11972,"component":"cluster","level":40,"msg":"worker 11978 died (1). restarting...","time":"2017-02-15T16:10:47.086Z","v":0}
{"name":"pump.io","
```

It's not consistent. I have been prevented from logging into identi.ca before, but today it works. Or might this be because identi.ca downgraded the other week?

**Comment by strugee** [comment] 2017-07-14 19:02
Looking at the stack trace this appears to be the same underlying cause as #1281. Not sure why the stack trace appears here and not in that case, but there it is.

In any case it should've been fixed by be6c1e46ebee1dde7f203017c0decb88c06b2a6f, so I'm closing as a dupe of #1281. Backported fix will go out shortly.

**Closed by strugee** 2017-07-14 19:02 UTC
Labels: bug
