### ISSUE TITLE
Newbie Question: Issues running UI - length not defined errors

### ISSUE THREAD

**Issue by mdgbayly** [pump-io/pump.io#1217] opened 2016-10-09 20:59 UTC
Just trying to get a pump.io server up and running in AWS. I'm new to NodeJS and Jade etc so I'm probably doing something really silly.

I'm getting lots of JS errors in the UI like:

```
TemplateError: login: Cannot read property 'length' of undefined
    at runTemplate (http://ec2-52-32-146-99.us-west-2.compute.amazonaws.com:31337/javascript/pump/view.js:235:32)
    at http://ec2-52-32-146-99.us-west-2.compute.amazonaws.com:31337/javascript/pump/view.js:286:17
    at Object.success (http://ec2-52-32-146-99.us-west-2.compute.amazonaws.com:31337/javascript/pump/view.js:204:29)
    at c (http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js:4:26036)
    at Object.fireWith [as resolveWith] (http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js:4:26840)
    at k (http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js:6:14258)
    at XMLHttpRequest.r (http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js:6:18646)
```

These errors seem to be coming from the layout.jade template.
There is code in the compiled template where it iterates the config scripts:

```
// iterate config.scripts
;(function(){
  var $$obj = config.scripts;
  if ('number' == typeof $$obj.length) {
```

But here the config object scripts is undefined which causes the error.
I'm not familar with Jade, or Jade templates compiled to run client side.
On the server side the config object has a default scripts property set to an empty array.

But on the client side there seems to be additional code at the end of layout.jade that initializes the client side config object with a few server side defaults. But scripts is not one of them.

So I'm kind of confused as to how this is all supposed to work - like i say - i'm a newb at this stuff - so i'm probably doing something silly but any pointers/insights would be greatly appreciated.

**Comment by mdgbayly** [comment] 2016-10-09 21:22
Hmm, just realized the Jade stuff is all pretty new, post the 1.0.0 release...
Maybe I should be running the 1.0.0 tag?
Is the Jade stuff expected to work yet?

**Comment by strugee** [comment] 2016-10-11 08:13
@mdgbayly generally speaking git master is always supposed to work. See https://github.com/pump-io/pump.io/wiki/Running-from-git-master

When you say "I'm getting lots of JS errors in the UI", what do you mean by that? Do you mean you're getting these errors in the web console? Is that traceback served to you as the body of a page (probably with an HTTP 500 Internal Server Error code?) Be as specific as possible.

When you say you're trying to get a server running in AWS, I assume you mean in an EC2 image? So basically a regular Linux environment?

Please also give us:

* A copy of your `pump.io.json` (with secrets removed, obviously) - here is preferable but if for whatever reason you'd like to keep it private you can email it to me at alex [at] strugee [dot] net
* _Exactly_ which version of pump.io you're running
* How you installed pump.io (via npm or via git clone?)

**Comment by strugee** [comment] 2016-10-11 08:15
Also, I notice you seem to have 31337 in your URLs - please make sure you read and understand https://github.com/pump-io/pump.io#making-changes

**Comment by mdgbayly** [comment] 2016-10-11 16:05
Yes, running on EC2. I used the instructions on this page/gist againast a standard AWS Ubuntu AMI.
https://github.com/pump-io/pump.io/wiki/Installation-on-Amazon-EC2-(Ubuntu)

The traceback I posted above is just coming from the browser web console. I'm not getting any errors on the server.  It seems like it's loading the compiled Jade templates client side and then having errors when running it. It seems like it has similar errors on many different pages presumably all caused by the same issues trying to render the layout.jade template client side.

Unfortunately, I've terminated that instance now so I cannot send you the exact pump.io.json, but I was just using the defaults from that gist.

I'm now running a local VM using Vagrant and the instructions here, but adjusted to use a local copy of pump.io with the 1.0.0 tag checked out.

https://github.com/pump-io/pump.io/wiki/Vagrant-Installation

This seems to be working fine, but obviously no longer using the Jade based UI.

When I get chance, I'll try switching this build back to the master build to see if I can replicate the issue.

But maybe you can clarify how the compiled client side templates are supposed to resolve the config from the server side.  It seems like in some places the server side config is being interpolated into the compiled template. 

e.g. here:

https://github.com/pump-io/pump.io/blob/master/public/template/layout.jade#L135

but in other places it is not:

e.g.  here:

https://github.com/pump-io/pump.io/blob/master/public/template/layout.jade#L124

So this latter line is relying on the client side Pump.config setup in line 135, which doesn't have the scripts property.

But like I said I don't know Jade and am pretty new to Node too, so I could have this all backwards.

**Comment by strugee** [comment] 2016-11-03 00:49
Turns out this was a regression since the Express 3.x merge. It's now mostly fixed and I'm currently squashing the remainder of the issues, so closing as resolved. Thanks for your bug report!

**Closed by strugee** 2016-11-03 00:49 UTC
