### ISSUE TITLE
lessen the amount of repetitive mongo failure logging

### ISSUE THREAD

**Issue by ian-kelling** [pump-io/pump.io#1661] opened 2018-06-13 14:59 UTC
Mongodb failed for some reason 2 days ago, which causes pump.io to fail, 
but I can't see the mongodb log in my systemd journal because the journal
is set to delete things beyond about 2gb of space, and pump.io output 732434 lines in 30 hours.
It repeated this every 2 seconds:

```
Jun 12 02:59:23 li pump[14551]:   name: 'MongoError',
Jun 12 02:59:23 li pump[14551]:   message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connec
Jun 12 02:59:25 li pump[14551]: { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: conn
Jun 12 02:59:25 li pump[14551]:     at Pool.<anonymous> (/usr/lib/node_modules/databank-mongodb/node_modules/mongodb-core/lib/
Jun 12 02:59:25 li pump[14551]:     at emitOne (events.js:116:13)
Jun 12 02:59:25 li pump[14551]:     at Pool.emit (events.js:211:7)
Jun 12 02:59:25 li pump[14551]:     at Connection.<anonymous> (/usr/lib/node_modules/databank-mongodb/node_modules/mongodb-cor
Jun 12 02:59:25 li pump[14551]:     at Object.onceWrapper (events.js:317:30)
Jun 12 02:59:25 li pump[14551]:     at emitTwo (events.js:126:13)
Jun 12 02:59:25 li pump[14551]:     at Connection.emit (events.js:214:7)
Jun 12 02:59:25 li pump[14551]:     at Socket.<anonymous> (/usr/lib/node_modules/databank-mongodb/node_modules/mongodb-core/li
Jun 12 02:59:25 li pump[14551]:     at Object.onceWrapper (events.js:315:30)
Jun 12 02:59:25 li pump[14551]:     at emitOne (events.js:116:13)
```

**Comment by strugee** [comment] 2018-06-13 20:59
Wow, that's no good. @ian-kelling are there any surrounding messages besides that in the systemd log? And can you post a bit from your `pump.io.log.json`?

I think this _may_ be a duplicate of #1402, but I'm not totally sure.

**Comment by ian-kelling** [comment] 2018-06-14 14:47
I think I need to turn on the pump.io.log.json. I should have mentioned that after starting mongo, everything started working normally. The original error probably was not pump.io.

**Comment by strugee** [comment] 2018-06-15 08:10
@ian-kelling yeah, that error is coming from the library `databank-mongodb` uses but we probably should still be ratelimiting it. If you don't have logs check your `nologger` and `logfile` config options. [Here's the reference](https://pumpio.readthedocs.io/en/latest/configuration/reference.html).

**Comment by strugee** [comment] 2018-12-17 20:12
Closing as a duplicate of #1402.

**Closed by strugee** 2018-12-17 20:12 UTC
Labels: admin, needs info
