### ISSUE TITLE
New feature : override config variables on the command line

### ISSUE THREAD

**Issue by h4ck3rm1k3** [pump-io/pump.io#1120] opened 2015-10-23 11:37 UTC
Yeah, if we could just be able to override configuration items on the command line,
that'd be great.

Example:

```
pump --config-children=1 --config-debug='--debug=1234'
```

**Comment by strugee** [comment] 2016-11-03 23:09
This will be possible when we switch to doing configuration through yargs. Closing as a duplicate of #1202

**Closed by strugee** 2016-11-03 23:09 UTC
