### ISSUE TITLE
Login form doesn't work with Iceweasel/Firefox:  doesn't get activated unless there is a key press on password field

### ISSUE THREAD

**Issue by evanp** [pump-io/pump.io#778] opened 2013-08-14 16:13 UTC
Something is wrong with Iceweasel and the login form. Maybe some other stuff, too.

Identi.ca has a lot of Iceweasel users because Debian.

**Comment by larjona** [comment] 2016-03-17 13:32
I don't experience web interface problems with Iceweasel since long time ago.
Maybe this issue can be closed?
I'll close it in the next month if nobody ask for keeping it open (and give reason).

**Comment by msjoberg** [comment] 2016-03-18 19:03
There is a bug that I see consistently with both Iceweasel and Chromium (the two browsers I have installed) that the Login button is disabled when it auto-fills my username and password. This might be due to the lack of any keyboard interaction. Maybe there is a JavaScript that interprets this as there not being any password. Typing something, e.g. just pressing the tab key to move to the next field enables the button.

**Comment by skellat** [comment] 2016-03-20 02:51
Is this an Iceweasel-only issue?  I could have sworn I had seen something where regular Firefox would displace Iceweasel at least in Unstable.  Whether that is backported down the line is something unclear to me in terms of making this moot.  If this is cropping up in Chromium too as stipulated by @msjoberg then there may be a deeper issue.

**Comment by strugee** [comment] 2016-03-20 22:09
@msjoberg see #463

**Comment by skellat** [comment] 2016-03-25 16:44
I thought Iceweasel is going away anyhow due to a settlement between Debian and Mozilla or will it still be supported in stable and older?

**Comment by strugee** [comment] 2016-03-25 20:33
Not sure. We should still investigate, though - I'm betting this is something not browser-specific, even if it's only exhibited in one browser.

**Comment by msjoberg** [comment] 2016-03-30 17:55
@strugee You're right, that's bug I'm thinking of, not this one. I still haven't seen any Iceweasel-specific bugs, though...

**Comment by kesara** [comment] 2016-08-27 03:54
I'm experiencing this on Iceweasel, Firefox and Firefox mobile with autofill / copy pasting password from a password manager.
Login button doesn't get activated unless there is a key press on password field.

**Comment by larjona** [comment] 2016-09-23 21:25
Can anybody test if the problem persists with the merged fix?

**Comment by strugee** [comment] 2016-09-24 04:49
@larjona I tested the referenced PR and it worked both in my local dev environment and in production at pump.strugee.net.

Closing given the above - if anyone can still reproduce this on Git master, comment and we'll reopen

**Closed by strugee** 2016-09-24 04:49 UTC
Labels: webui
