### ISSUE TITLE
npm test occasionally yields "weird error" but hangs most of the time. pump instance seems to work

### ISSUE THREAD

**Issue by michaelbrunnbauer** [pump-io/pump.io#811] opened 2013-09-06 12:39 UTC
node-v0.10.17 installed globally
GraphicsMagick-1.3.18 installed globally
mongodb-linux-x86_64-2.4.6 installed globally and running
pump.io 0.3.0-alpha.1 installed locally
databank-mongodb installed locally in node_modules/databank

npm test occasionally yields this:

â Errored Â» callback not fired
      in When we require the event module and we get its Event class export and we create an event instance
      in event module interface
      in test/event-test.jsâ Errored Â» 779 honored â 1 broken â 1 errored â 3 dropped

npm ERR! weird error 1
npm ERR! not ok code 0

But most of the time it runs for some time and then hangs with the node process sleeping.

My instance seems to work nevertheless: https://pump.brunni.de/brunni

BTW: How do I do upgrades of pump.io ? Will a fresh install of a new version work with the old config file and database ?

**Comment by strugee** [comment] 2016-12-15 06:47
Closing as a dupe of #1228 (even though that's the newer one) because the newer one has more info. Thanks for reporting this!

**Closed by strugee** 2016-12-15 06:47 UTC
