### ISSUE TITLE
vagrant setup docs outdated

### ISSUE THREAD

**Issue by dissolve** [pump-io/pump.io#1324] opened 2017-04-06 18:55 UTC
https://github.com/pump-io/pump.io/wiki/Vagrant-Installation does not work.

IanKelling on IRC suggested that it may be node / npm versions are too old in the image listed.  

from screenlog.0

> pump.io@4.0.0-alpha.0 start /srv/pump.io
> ./bin/pump

module.js:340
    throw err;
          ^
Error: Cannot find module 'bunyan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/srv/pump.io/bin/pump:29:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

npm ERR! pump.io@4.0.0-alpha.0 start: `./bin/pump`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the pump.io@4.0.0-alpha.0 start script.
npm ERR! This is most likely a problem with the pump.io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/pump
npm ERR! You can get their info via:
npm ERR!     npm owner ls pump.io
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-116-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /srv/pump.io
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /srv/pump.io/npm-debug.log
npm ERR! not ok code 0

**Comment by strugee** [comment] 2017-04-06 20:47
As I said on IRC the instructions in that wiki page aren't officially supported or recommended by us. It is unfortunate that they don't work, though, so I'll add a note at the top of the wiki page.

Official, in-tree Vagrant support is tracked in #1302.

**Comment by strugee** [comment] 2017-04-07 07:13
I added a note to the wiki page stating that it's outdated/not supported. Closing as a duplicate of #1302.

**Closed by strugee** 2017-04-07 07:13 UTC
